spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
      # ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://ec2-3-216-113-109.compute-1.amazonaws.com:5432/dl3hr4o1i67ug
    username: ghprmcmxawpbaz
    password: cc5f5d2e600a5c589b4bd3b39a0b6bed4e1fbf1901fa58e8aa4ee88215426cb2
    driverClassName: org.postgresql.Driver
