server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: api-product
          uri: http://localhost:8081/
          predicates:
            - Path=/api/v1/products/**
        - id: api-user
          uri: http://localhost:8082/
          predicates:
            - Path=/api/v1/users/**
        - id: api-order
          uri: http://localhost:8083/
          predicates:
            - Path=/api/v1/orders/**
        - id: api-payment
          uri: http://localhost:8084/
          predicates:
            - Path=/api/v1/payments/**